services:
  - type: web
    name: voos-baratos-backend
    runtime: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8787
      - key: DUFFEL_MODE
        value: test
      - key: DUFFEL_ACCESS_TOKEN
        sync: false
